# Generated by Django 4.2 on 2024-05-23 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='money_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_money', models.PositiveBigIntegerField()),
                ('spent_money', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('phone_number', models.BigIntegerField()),
                ('monthly_money', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('money', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.money_history')),
            ],
        ),
    ]
