# Generated by Django 4.0 on 2024-05-22 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='user',
            new_name='organization_staff',
        ),
    ]
