# Generated by Django 5.0.6 on 2024-05-22 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('organization', '0002_organization_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='employees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_for_organization', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='organization',
            name='monthly_money',
            field=models.IntegerField(default=0),
        ),
    ]
