# Generated by Django 5.0.6 on 2024-05-22 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_organization_employees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='employees',
        ),
    ]
