# Generated by Django 4.0 on 2024-05-22 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.BigIntegerField()),
                ('age', models.DateField()),
                ('is_married', models.BooleanField(default=False)),
                ('children', models.IntegerField()),
                ('is_divorced', models.BooleanField(default=False)),
                ('salary', models.IntegerField()),
                ('hired_at', models.DateField()),
                ('passport_id', models.CharField(max_length=20)),
                ('handicapped', models.CharField(choices=[('0', 'Nogiron emas'), ('1', '1-darajali'), ('2', '2-darajali'), ('3', '3-darajali')], default='0', max_length=1)),
                ('role', models.CharField(max_length=100)),
                ('current_health', models.CharField(max_length=100)),
                ('illness', models.CharField(max_length=100)),
                ('family_health', models.CharField(max_length=100)),
                ('underages', models.IntegerField()),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
        ),
    ]
