# Generated by Django 4.0 on 2024-05-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.BigIntegerField()),
                ('age', models.DateTimeField()),
                ('is_married', models.BooleanField(default=False)),
                ('children', models.IntegerField()),
                ('is_dicorced', models.BooleanField(default=False)),
                ('salary', models.IntegerField()),
                ('hired_at', models.DateTimeField()),
                ('passport_id', models.IntegerField()),
                ('is_handicapped', models.BooleanField(default=False)),
                ('role', models.CharField(max_length=100)),
                ('current_health', models.CharField(max_length=100)),
                ('illness', models.CharField(max_length=100)),
                ('family_health', models.CharField(max_length=100)),
                ('underages', models.IntegerField()),
            ],
        ),
    ]
