# Generated by Django 4.0 on 2024-05-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_children_alter_employee_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='children',
            field=models.IntegerField(default=0),
        ),
    ]
