# Generated by Django 4.0 on 2024-05-22 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_overall_bal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='children',
        ),
    ]
