# Generated by Django 4.0 on 2024-05-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_remove_employee_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='handicapped',
            field=models.CharField(choices=[('0', 'Nogiron emas'), ('2', '2-darajali'), ('3', '3-darajali')], default='0', max_length=1),
        ),
    ]
