# Generated by Django 4.0 on 2024-05-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_employee_handicapped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='illness',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('1', 'Erkak'), ('1.3', 'Ayol')], default='1', max_length=5),
        ),
        migrations.AddField(
            model_name='employee',
            name='has_illness',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_role',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='handicapped',
            field=models.CharField(choices=[('0', 'Nogiron emas'), ('3', '2-darajali'), ('2', '3-darajali')], default='0', max_length=1),
        ),
    ]
