# Generated by Django 4.0 on 2024-05-22 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_remove_employee_illness_remove_employee_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='current_health',
        ),
    ]
